server:
  port: 18082
spring:
  application:
    name: service-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:18848
    sentinel:
      transport:
        dashboard: localhost:18080
    gateway:
      routes:
        - id: service-consumer-feign        # 路由id，没有固定规则，但唯一，建议与服务名对应
#          uri: http://localhost:18081      # 匹配后提供服务的路由地址
          uri: lb://service-consumer        # 动态路由，使用服务名代替上面的IP带端口
          predicates:
            #以下是断言条件，必须全部符合条件
            - Path=/user/feign/**               #断言，路径匹配 注意：Path 中 P 为大写
            - Method=GET                       #只能时 GET 请求时，才能访问