server:
  port: 18082
spring:
  application:
    name: service-gateway
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 10s
    lettuce:
      pool:
        max-active: 8
        max-wait: -1s
        max-idle: 8
        min-idle: 0
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: localhost:18080
    gateway:
      routes:
        - id: service-consumer-feign        # 路由id，没有固定规则，但唯一，建议与服务名对应
#          uri: http://localhost:18081      # 匹配后提供服务的路由地址
          uri: lb://service-consumer        # 动态路由，使用服务名代替上面的IP带端口
          predicates:
            #以下是断言条件，必须全部符合条件
            - Path=/user/feign/**              #断言，路径匹配 注意：Path 中 P 为大写
            - Method=GET                       #只能时 GET 请求时，才能访问
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@pathKeyResolver}"        # 限流键解析器的bean名称
                redis-rate-limiter.replenishRate: 1        # 每秒填充令牌数，每秒处理能力
                redis-rate-limiter.burstCapacity: 5        # 令牌桶容量，处理瞬时流量的能力
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@remoteAddrKeyResolver}"  # 限流键解析器的bean名称
                redis-rate-limiter.replenishRate: 1        # 每秒填充令牌数
                redis-rate-limiter.burstCapacity: 5        # 令牌桶容量